name: Deploy Power Platform Solution (Managed)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    env:
      SOLUTION_NAME: CostcoDev
      SOLUTION_PATH: Solution/CostcoDev
      PACKED_OUTPUT: packed
      ZIP_NAME: CostcoDev_managed.zip
      TARGET_ENVIRONMENT_URL: https://org3cd22ca1.crm.dynamics.com

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Power Platform CLI
      run: |
        iex "& { $(irm https://aka.ms/pac/install) }"
        pac install latest

    - name: Pack Solution (Managed)
      run: |
        mkdir $env:PACKED_OUTPUT
        pac solution pack `
          --path "$env:SOLUTION_PATH" `
          --packagetype Managed `
          --outputDirectory "$env:PACKED_OUTPUT"

    - name: Authenticate to Target Environment
      run: |
        pac auth clear
        pac auth create `
          --clientId "${{ secrets.CLIENT_ID  }}" `
          --clientSecret "${{ secrets.CLIENT_SECRET }}" `
          --tenant "${{ secrets.TENANT_ID }}" `
          --url "https://org3cd22ca1.crm.dynamics.com"

    - name: Import Solution
      run: |
        pac solution import `
          --path "$env:PACKED_OUTPUT\\$env:ZIP_NAME"
