name: Export Power Platform Solution

on:
  workflow_dispatch:

jobs:
  export-solution:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Power Platform CLI
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Verify PAC CLI
        run: pac help

      - name: Authenticate with Power Platform
        run: |
          pac auth create --applicationId ${{ secrets.CLIENT_ID }} --clientSecret ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }} --environment https://rsmradev.crm.dynamics.com

      - name: Export and unpack solution
        run: |
          pac solution export --name CostcoDev --path CostcoDev.zip --managed false
          pac solution unpack --zipfile CostcoDev.zip --folder unpacked --packagetype Unmanaged

      - name: Push changes to test_deployment branch
        shell: bash
        run: |
          git config user.name "Upendra"
          git config user.email "Upendra.Singh@rsmpf.onmicrosoft.com"
          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Exported solution on $(date)"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
          fi
